### ISSUE TITLE
Volume still in mounted=true state after pod has volume unmounted

### ISSUE THREAD

**Issue by robinbraemer** [storageos/cluster-operator#133]
The StorageOS volume's mount state is not switching to false after the volume is unmounted.

Steps to reproduce:
- create a volume `storageos-volume-test` in storageos
- apply following yaml after updating secret to access your storageos cluster:
```
apiVersion: v1
data:
  apiAddress: XXXXXXXXXX
  apiPassword: XXXXXXXXXX
  apiUsername: XXXXXXXXXX
kind: Secret
metadata:
  name: storageos-secret-test
type: "kubernetes.io/storageos"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-issue
spec:
  terminationGracePeriodSeconds: 0
  volumes:
    - name: vol
      storageos:
        volumeName: storageos-volume-test
        secretRef:
          name: storageos-secret-test
  containers:
    - image: busybox
      name: busybox
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: /data/test
          name: vol
```

The pod is successfully mounting to the fresh volume.
Now when deleting the pod `kubectl delete pod test-issue` and looking up the volume (with the client or GUI) the volume's `mounted` state is still `true`, which should be `false` because the deleted pod is not longer using the volume.

Also when running the client: `storageos volume rm YOUR_NS/storageos-volume-test` the output is as expected `API error (Precondition Failed): cannot delete mounted volume 'YOUR_NS/storageos-volume-test'`.

*I also have a quick question: How can I create a snaphot/copy of a volume?*

**Additional info:**

```
storageos version`
Client:
 Version:      1.2.1
 API version:  1
 Go version:   go1.12.4
 Git commit:   8e7f857
 Built:        2019-05-15T150300Z
 OS/Arch:      linux/amd64

Server:
 Version:      1.2.1
 API version:  1
 Go version:   go1.11.5
 Git commit:   68ca908
 Built:        2019-05-15T164954Z
 OS/Arch:      linux/amd64
 Experimental: false
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Deployed using helm storageos-operator version 0.2.6

**Comment by avestuk** [comment]
@robinbraemer What Kubernetes version are you running and are you using the CSI driver or the native driver?

**Comment by robinbraemer** [comment]
I have `cluster.csi.enable` enabled

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by avestuk** [comment]
@robinbraemer Thanks. Could you share your volume definition as well please? I'm a little thrown by the way the volume is being referenced in your pod definition. Typically volumes would be created as a persistentVolumeClaim and referenced that way. 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: d1
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: debian
      image: debian:9-slim
      command: ["/bin/sleep"]
      args: [ "3600" ]
      volumeMounts:
        - mountPath: /mnt
          name: v1
  volumes:
    - name: v1
      persistentVolumeClaim:
        claimName: pvc-1
```

The storageos secret doesn't need to be referenced when using CSI as Kubernetes-StorageOS communication takes place using a socket rather than the StorageOS API.
