### ISSUE TITLE
Problem with AKS storage

### ISSUE THREAD

**Issue by michalalter** [storageos/cluster-operator#257]
Hi all,

Am I missing smth or I don't see any capabilities to install storageos (even 2.x version) on dedicated pvcs attached to the nodes in clouds Kubernetes distrubutions?
For example this possibility has rook - could be provisioned and use pvc mounts from osd pods
The relevant part of rook:

```yaml
        spec:
          resources:
            requests:
              storage: 128Gi
          storageClassName: managed-premium
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
```
The scenario is that in clouds like Azure  - cloud creates AKS nodes without possibility to manipulate local storage
On the other hand, I could do some workarounds like initcontainers invoking /var/lib/storageos space covered by azure-disk but I'm expecting storageos to do that..
I'm expecting the possibility to point /var/lib/storageos into PVC volume

Regards,
Michal
