### ISSUE TITLE
Node containers can't connect to ETCD

### ISSUE THREAD

**Issue by nsoubelet** [storageos/cluster-operator#296]
Hi there,
I am trying to deploy storageos for testing but I could not make node containers (`storageos-daemonset-xyz`) connect to etcd. I tried two different options:

1. Use an external etcd cluster I have.
2. Create an etcd cluster inside k8s cluster, as suggested in your documentation https://docs.storageos.com/v2.1/docs/prerequisites/etcd/

This is what log spits out:
```
{"level":"debug","msg":"tracing is disabled","time":"2020-12-08T21:44:36.779463135Z"}
{"level":"debug","msg":"tracer created successfully","time":"2020-12-08T21:44:36.779626243Z"}
{"config_file_path":"/var/lib/storageos/config.json","level":"debug","msg":"local file configuration persistence ready","time":"2020-12-08T21:44:36.779691175Z"}
{"file_config_joined_cluster":"24a3c885-ebac-4b69-871b-07b7605bbbb9","file_config_local_node_id":"a2274eee-f6d0-4055-a8e3-f2189a44c0c9","file_config_node_created_at":"2020-12-08T15:40:17Z","level":"debug","msg":"read stored file configuration","time":"2020-12-08T21:44:36.779818426Z"}
{"level":"info","msg":"starting StorageOS","time":"2020-12-08T21:44:36.779878308Z"}
{"env_advertise_address":"x.y.z.k","env_api_bind_address":"","env_api_tls_ca":"","env_bind_address":"","env_bootstrap_namespace":"","env_bootstrap_username":"admin","env_csi_endpoint":"unix:///var/lib/kubelet/plugins_registry/storageos/csi.sock","env_csi_version":"v1","env_dataplane_daemon_dir":"","env_dataplane_dir":"","env_device_dir":"","env_dial_timeout":"","env_disable_crash_reporting":"false","env_disable_telemetry":"false","env_disable_version_check":"false","env_etcd_endpoints":"storageos-etcd-client.storageos-etcd.svc.xyz:2379","env_etcd_namespace":"","env_etcd_tls_client_ca":"","env_etcd_tls_client_cert":"","env_etcd_tls_client_key":"","env_etcd_username":"","env_gossip_advertise_address":"","env_gossip_bind_address":"","env_health_grace_period":"","env_health_probe_interval":"","env_health_probe_timeout":"","env_hostname":"xyz","env_internal_api_advertise_address":"","env_internal_api_bind_address":"","env_internal_tls_ca_cert":"","env_internal_tls_node_cert":"","env_internal_tls_node_key":"","env_io_advertise_address":"","env_io_bind_address":"","env_jaeger_endpoint":"","env_jaeger_service_name":"","env_k8s_config_path":"","env_k8s_distribution":"upstream","env_k8s_enable_scheduler_extender":"true","env_k8s_namespace":"kube-system","env_log_file":"","env_log_format":"json","env_log_level":"xdebug","env_log_size_limit":"","env_node_capacity_interval":"","env_root_dir":"","env_socket_dir":"","env_supervisor_advertise_address":"","env_supervisor_bind_address":"","level":"info","msg":"environment variables at startup","time":"2020-12-08T21:44:36.779983858Z"}
{"bin_build_date":"2020-06-23T13:13:48.474931189+00:00","bin_build_ref":"","bin_git_branch":"release/v2.1.0","bin_git_commit_hash":"404e6917a7859c9419897be06299b5704fbbc4b1","bin_version":"2.1.0","level":"debug","msg":"version information","time":"2020-12-08T21:44:36.780135244Z"}
{"level":"debug","msg":"got persisted configuration from cache","time":"2020-12-08T21:44:36.780218711Z"}
{"level":"debug","msg":"read node ID from persisted config","time":"2020-12-08T21:44:36.780299874Z"}
{"level":"info","msg":"local node StorageOS id: a2274eee-f6d0-4055-a8e3-f2189a44c0c9","time":"2020-12-08T21:44:36.780370056Z"}
{"level":"info","msg":"local node Hostname is: xyz","time":"2020-12-08T21:44:36.780427004Z"}
{"error":"no TLS ca certificate provided","level":"warning","msg":"no TLS certificate provided for etcd, communications will not be secured","time":"2020-12-08T21:44:36.780488098Z"}
{"level":"debug","msg":"connecting to ETCD at: [storageos-etcd-client.storageos-etcd.svc.xyz:2379]","time":"2020-12-08T21:44:36.780537663Z"}
{"endpoints":["storageos-etcd-client.storageos-etcd.svc.xyz:2379"],"error":"context deadline exceeded","level":"error","msg":"unable to connect to etcd","store":"etcd","time":"2020-12-08T21:44:41.780858551Z"}
{"error":"failed to instantiate ETCD: context deadline exceeded","level":"error","msg":"failed to initialise store client","time":"2020-12-08T21:44:41.780958599Z"}
{"level":"info","msg":"shutting down","time":"2020-12-08T21:44:41.780982726Z"}
{"level":"debug","msg":"shutting down subsystem","subsystem_name":"tracer","time":"2020-12-08T21:44:41.780997343Z"}
```
Some important comments:

1. I always get the same message, for internal and external etcd.
2. I ran a test pod with a simple `netcat` against the service/endpoint in the same namespace where node container runs and resolves OK.
3. Also tried a `etcdctl --endpoints=http://storageos-etcd-client.storageos-etcd.svc.xyz:2379 member list` and works OK.
4. etcd clusters are insecure, so do not require tls info.
5. K8s cluster has more than 100 pods and services defined a communicating each other so I doubt problem is related to Kubernetes itself.

So at this point I wonder if you could help me to determine the cause, maybe it is only a misconfiguration.

Thanks!

**Comment by aeroniero33** [comment]
Hi @nsoubelet ,

Could you send us over the StorageOS Cluster CR please? You can do that with `kubectl describe stos -A`

Could you also make sure that you have all the relevant firewall ports open? (https://docs.storageos.com/docs/prerequisites/firewalls/)

Also, is there a reason you are using v2.1? The newest version is [v2.3.2](https://docs.storageos.com/docs/install/kubernetes/).

**Comment by nsoubelet** [comment]
Hi @aeroniero33 
Thanks for replying.
Unfortunately I have uninstalled StorageOS but I will give it another try and send it over.
 
> Could you also make sure that you have all the relevant firewall ports open?

Yes, firewalls open, that's why I clarified points 2 and 3 in my issue.
> Also, is there a reason you are using v2.1? The newest version is v2.3.2.

I first tried with latest, then I tried other versions just is case there was a particular issue in that version, but it is failing in all 2.x versions.

**Comment by coneking** [comment]
Hi @nsoubelet, 
I know that your ETCD cluster are insecure but I had the same issue whit tls, in my case the problem was the secret resource `storageos-tls-etcd`.
When I created storageoscluster for the frst time, a secret was created (storageos-tls-etcd), this secret is used by Daemonset `storageos-daemonset` to comunicate Pods with the cluster ETCD, this secret contains the tls certs. 
Then I uninstalled storageoscluster and install again (by some errors), but this secret still existed and my pods could not connect to the cluster ETCD (same error `"{"error":"failed to instantiate ETCD: context deadline exceeded","level":"error","msg":"failed to initialise store client","time":"2020-12-08T21:44:41.780958599Z"}"`).
To solve this just delete that secret en reinstall storageos and storageoscluster. I hope this helps.

**Comment by nsoubelet** [comment]
Hi @coneking 
Many thanks for sharing. Really interesting, I will give it a try for sure!

**Comment by nsoubelet** [comment]
Hi @coneking, I tried what you said with no luck. I don't see any secret being created by storage os apart from tokens. Maybe you are using a different version?.

@aeroniero33, please find bellow the output of the command. Some sensitive fields were replaced.

```
Name:         example-storageos
Namespace:    storageos-operator
Labels:       <none>
Annotations:  API Version:  storageos.com/v1
Kind:         StorageOSCluster
Metadata:
  Creation Timestamp:  2021-01-03T19:16:41Z
  Finalizers:
    finalizer.storageoscluster.storageos.com
  Generation:  3
  Managed Fields:
    API Version:  storageos.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:debug:
        f:images:
          .:
          f:nodeContainer:
        f:k8sDistro:
        f:kvBackend:
          .:
          f:address:
          f:backend:
        f:nodeSelectorTerms:
        f:resources:
          .:
          f:requests:
            .:
            f:memory:
        f:secretRefName:
        f:secretRefNamespace:
    Manager:      kubectl
    Operation:    Update
    Time:         2021-01-03T19:16:41Z
    API Version:  storageos.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
      f:spec:
        f:csi:
          .:
          f:deploymentStrategy:
          f:enable:
          f:enableControllerExpandCreds:
          f:enableControllerPublishCreds:
          f:enableNodePublishCreds:
          f:enableProvisionCreds:
        f:images:
          f:apiManagerContainer:
          f:csiClusterDriverRegistrarContainer:
          f:csiExternalAttacherContainer:
          f:csiExternalProvisionerContainer:
          f:csiExternalResizerContainer:
          f:csiLivenessProbeContainer:
          f:csiNodeDriverRegistrarContainer:
          f:initContainer:
          f:kubeSchedulerContainer:
        f:ingress:
        f:join:
        f:namespace:
        f:resources:
          f:requests:
            f:cpu:
        f:service:
          .:
          f:externalPort:
          f:internalPort:
          f:name:
          f:type:
      f:status:
        .:
        f:members:
          .:
          f:unready:
        f:nodes:
        f:phase:
        f:ready:
    Manager:         cluster-operator
    Operation:       Update
    Time:            2021-01-03T19:16:47Z
  Resource Version:  3106986
  Self Link:         /apis/storageos.com/v1/namespaces/storageos-operator/storageosclusters/example-storageos
  UID:               67436d62-b8f4-4d2b-819b-ed02c2073419
Spec:
  Csi:
    Deployment Strategy:              deployment
    Enable:                           true
    Enable Controller Expand Creds:   true
    Enable Controller Publish Creds:  true
    Enable Node Publish Creds:        true
    Enable Provision Creds:           true
  Debug:                              true
  Images:
    API Manager Container:                   storageos/api-manager:v1.0.0
    Csi Cluster Driver Registrar Container:  quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
    Csi External Attacher Container:         quay.io/k8scsi/csi-attacher:v2.2.0
    Csi External Provisioner Container:      storageos/csi-provisioner:v1.6.0-patched
    Csi External Resizer Container:          quay.io/k8scsi/csi-resizer:v0.5.0
    Csi Liveness Probe Container:            quay.io/k8scsi/livenessprobe:v1.1.0
    Csi Node Driver Registrar Container:     quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
    Init Container:                          storageos/init:v2.1.0
    Kube Scheduler Container:                k8s.gcr.io/kube-scheduler:v1.18.4
    Node Container:                          storageos/node:v2.3.1
  Ingress:
  Join:       [some-ip]
  k8sDistro:  upstream
  Kv Backend:
    Address:  http://[service]:2379
    Backend:  etcd
  Namespace:  kube-system
  Node Selector Terms:
    Match Expressions:
      Key:       [some-key]
      Operator:  In
      Values:
        [some-val]
  Resources:
    Requests:
      Cpu:               1
      Memory:            256Mi
  Secret Ref Name:       storageos-api
  Secret Ref Namespace:  storageos-operator
  Service:
    External Port:  5705
    Internal Port:  5705
    Name:           storageos
    Type:           ClusterIP
Status:
  Members:
    Unready:
      [some-ip]
  Nodes:
    [some-ip]
  Phase:  Creating
  Ready:  0/1
Events:
  Type     Reason         Age    From                       Message
  ----     ------         ----   ----                       -------
  Warning  ChangedStatus  6m10s  storageoscluster-operator  0/1 StorageOS nodes are functional

```

**Comment by coneking** [comment]
Hi @nsoubelet, 

The secret was created automatically in kube-system

```sh
kubectl -n kube-system get secret storageos-tls-etcd
```


Am using v2.3.1 and v2.3.2 on different clusters

```yaml
apiVersion: storageos.com/v1
kind: StorageOSCluster
metadata:
  finalizers:
  - finalizer.storageoscluster.storageos.com
  name: example-storageos
  namespace: storageos-operator
spec:
  csi:
    deploymentStrategy: deployment
    enable: true
    enableControllerExpandCreds: true
    enableControllerPublishCreds: true
    enableNodePublishCreds: true
    enableProvisionCreds: true
  images:
    apiManagerContainer: storageos/api-manager:v1.0.0
    csiClusterDriverRegistrarContainer: quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
    csiExternalAttacherContainer: quay.io/k8scsi/csi-attacher:v2.2.0
    csiExternalProvisionerContainer: storageos/csi-provisioner:v1.6.0-patched
    csiExternalResizerContainer: quay.io/k8scsi/csi-resizer:v0.5.0
    csiLivenessProbeContainer: quay.io/k8scsi/livenessprobe:v1.1.0
    csiNodeDriverRegistrarContainer: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
    initContainer: storageos/init:v2.1.0
    kubeSchedulerContainer: k8s.gcr.io/kube-scheduler:v1.16.7
    nodeContainer: storageos/node:v2.3.2
  ingress: {}
  join: ALL-MY-NODES
  k8sDistro: upstream
  kvBackend:
    address: MY-SERVERS-ETCD:2379
    backend: etcd
  namespace: kube-system
  resources:
    requests:
      cpu: "1"
      memory: 512Mi
  secretRefName: storageos-api
  secretRefNamespace: storageos-operator
  service:
    externalPort: 5705
    internalPort: 5705
    name: storageos
    type: ClusterIP
  tlsEtcdSecretRefName: MY-SECRET-TLS
  tlsEtcdSecretRefNamespace: kube-system
```
